cohpy_project/apps/library/urls.py
from django.conf.urls.defaults import *
from library.models import Publisher, Book
from library.forms import CheckoutForm

publisher_list = {
    "queryset": Publisher.objects.all(),
}
book_list = {
    "queryset": Book.objects.all(),
}

urlpatterns = patterns("django.views.generic.list_detail",
    url(r"^publishers/(?P<slug>[-\w]+)/$",
        view="object_detail",
        kwargs=publisher_list,
        name="book_publisher_detail",
    ),
    url (r"^publishers/$",
        view="object_list",
        kwargs=publisher_list,
        name="book_publisher_list",
    ),
    url(r"^(?P<slug>[-\w]+)/$",
        view="object_detail",
        kwargs=book_list,
        name="book_detail",
    ),
    url (r"^$",
        view="object_list",
        kwargs=book_list,
        name="book_list",
    ),
)
urlpatterns += patterns("library.views",
    url(r"^review/(?P<book_pk>[\d]+)/$", "review", name="add_review"),
    url(r"^review/(?P<book_pk>[\d]+)/(?P<review_pk>[\d]+)/$", "review", name="edit_review"),
    url(r"^checkout/(?P<book_pk>[\d]+)/$", "checkout", name="checkout"),
    url(r"^checkout/(?P<book_pk>[\d]+)/(?P<checkout_pk>[\d]+)/$", "checkout", name="edit_checkout"),
    url(r"^checkout/(?P<book_pk>[\d]+)/(?P<checkout_pk>[\d]+)/(?P<checkin>checkin)/$", "checkout", name="checkin"),
)

cohpy_project/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

from django.contrib import admin
admin.autodiscover()

from servee import frontendadmin
frontendadmin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
    url(r"^library/", include("library.urls")),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/", include(PinaxConsumer().urls)),
    url(r"^meetings/", redirect_to, {"url": "http://www.meetup.com/Central-Ohio-Python-Users-Group/"}),
    url(r"^servee/", include(frontendadmin.site.urls)),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

cohpy_project/apps/library/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import permalink
from easy_thumbnails.fields import ThumbnailerImageField
import datetime

class Book(models.Model):
    """Listing of books"""
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    prefix = models.CharField(max_length=20, blank=True)
    subtitle = models.CharField(blank=True, max_length=255)
    slug = models.SlugField(unique=True)
    isbn = models.CharField(max_length=14, blank=True)
    pages = models.PositiveSmallIntegerField(blank=True, null=True, default=0)
    publisher = models.ForeignKey("Publisher", blank=True, null=True)
    published = models.DateField(blank=True, null=True)
    cover = ThumbnailerImageField(
        upload_to='book_covers',
        resize_source=dict(size=(800, 1600)),
    )
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'books'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.full_title

    @property
    def full_title(self):
        if self.prefix:
            return '%s %s' % (self.prefix, self.title)
        else:
            return '%s' % self.title

    @permalink
    def get_absolute_url(self):
        return ('book_detail', None, { 'slug': self.slug })
    
    @property
    def is_out(self):
        if self.checkout_set.filter(date_returned__isnull=True).count():
            return True
        return False

    def out_to(self):
        """
        This is not a very safe method. your data could get screwed up, or you could 
        call this method when no user has checked this out.  Just an example of 
        something stupid you can do with class methods
        """
        return self.checkout_set.get(date_returned__isnull=True)

    @property
    def amazon_url(self):
        if self.isbn:
            try:
                return 'http://www.amazon.com/dp/%s/?%s' % (self.isbn, settings.AMAZON_AFFILIATE_EXTENTION)
            except:
                return 'http://www.amazon.com/dp/%s/' % self.isbn
        return ''


class Publisher(models.Model):
    """Publisher"""
    title = models.CharField(max_length=100)
    prefix = models.CharField(max_length=20, blank=True)
    slug = models.SlugField(unique=True)
    website = models.URLField(blank=True, verify_exists=False)
    logo = ThumbnailerImageField(
        upload_to='publisher_logos',
        resize_source=dict(size=(400, 400)),
    )

    class Meta:
        db_table = 'book_publishers'
        ordering = ('title',)

    def __unicode__(self):
        return '%s' % self.full_title

    @property
    def full_title(self):
        return '%s %s' % (self.prefix, self.title)

    @permalink
    def get_absolute_url(self):
        return ('book_publisher_detail', None, { 'slug':self.slug })

class Checkout(models.Model):
    date = models.DateField(default=datetime.datetime.now())
    user = models.ForeignKey(User)
    date_returned = models.DateField(blank=True, null=True)
    book = models.ForeignKey(Book)

class Review(models.Model):
    CHOICES = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    date = models.DateField(auto_now=True)
    user = models.ForeignKey(User)
    book = models.ForeignKey(Book)
    why_did_you_get_this_book = models.TextField(blank=True, null=True)
    did_you_like_it = models.TextField(blank=True, null=True)
    stars = models.IntegerField(choices=CHOICES)

cohpy_project/apps/library/forms.py
from django import forms
from django.contrib.auth.models import User
import datetime

from library.models import Book, Checkout, Review

class CheckoutForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=User.objects.all())
    book = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=Book.objects.all())
        
    def __init__(self, *args, **kwargs):
        book = kwargs.pop("book", None)
        user = kwargs.pop("user", None)
        if book is None or user is None:
            raise "did not pass book and user in"
        super(CheckoutForm, self).__init__(*args, **kwargs)
        self.fields["book"].initial = book
        self.fields["user"].initial = user
    
    class Meta:
        exclude = ["date", "date_returned",]
        model = Checkout

class ReviewForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=User.objects.all())
    book = forms.ModelChoiceField(widget=forms.HiddenInput(), queryset=Book.objects.all())
    
    def __init__(self, *args, **kwargs): 
        book = kwargs.pop("book", None)
        user = kwargs.pop("user", None)
        if book is None or user is None:
            raise "did not pass book and user in"
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields["book"].initial = book
        self.fields["user"].initial = user
    
    class Meta:
        model = Review

cohpy_project/apps/library/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.template import RequestContext
import datetime

from library.forms import CheckoutForm, ReviewForm
from library.models import Book, Checkout, Review


@login_required
def review(request, book_pk, review_pk=None):
    book = get_object_or_404(Book, pk=book_pk)
    if review_pk:
        review = get_object_or_404(Review, pk=review_pk)
        if review.user != request.user:
            return HttpResponseForbidden("Hey! Don't do that!")
    else:
        review = None
    form = ReviewForm(request.POST or None, book=book, user=request.user, instance=review)
    
    if form.is_valid():
        # use commit=False to keep making changes to the model
        # after you save the form
        review = form.save(commit=False)
        
        # Force the user, just in case any maliciousness has happened
        # on the level of the form
        review.user = request.user
        
        review.save()
        ##@@ Add a message
        return redirect("book_detail", book.slug)
    
    if request.is_ajax():
        template = "library/_review_form.html"
    else:
        template = "library/review_form.html"
    
    return render_to_response(template, {
        "form": form,
        "book": book,
        "review": review
    }, context_instance=RequestContext(request))


@login_required
def checkout(request, book_pk, checkout_pk=None, checkin=False):
    book = get_object_or_404(Book, pk=book_pk)
    if checkout_pk:
        checkout = get_object_or_404(Checkout, pk=checkout_pk)
        if checkout.user != request.user:
            return HttpResponseForbidden("Hey! Don't do that!")
    else:
        checkout = None
    form = CheckoutForm(request.POST or None, book=book, user=request.user, instance=checkout)
    
    if form.is_valid():
        # use commit=False to keep making changes to the model
        # after you save the form
        checkout = form.save(commit=False)
        
        # Force the user, just in case any maliciousness has happened
        # on the level of the form
        checkout.user = request.user
        
        if checkin in [True, "True", "true", "t", "T", "checkin", "CHECKIN"]:
            checkout.date_returned = datetime.datetime.now()
        
        checkout.save()
        
        ##@@ Add a message        
        return redirect("book_detail", book.slug)
    
    if request.is_ajax():
        template = "library/_checkout_form.html"
    else:
        template = "library/checkout_form.html"
    
    if checkin in [True, "True", "true", "t", "T", "checkin", "CHECKIN"]:
        checkin = "Check In"
    else:
        checkin = "Check Out"
        
    return render_to_response(template, {
        "form": form,
        "book": book,
        "checkout": checkout,
        "checkin": checkin,
    }, context_instance=RequestContext(request))

cohpy_project/templates/library/_checkout_form.html
{% with checkin as form_submit %}
{% include "library/_form.html" %}
{% endwith %}

cohpy_project/templates/library/_form.html
{% load uni_form_tags %}
<form action="{{ form_action|default:request.path }}" method="POST" class="uniForm">
    {% csrf_token %}
        {{ form|as_uni_form }}
        <div class="buttonHolder">
            <input type="submit"
                    name=""
                    value="{{ form_submit|default:"Submit" }}"
                        class="button"
                        id="button-id-submit"
                    />
        </div>
    </fieldset>{% comment %}I know this doesn't look right in the template, but checkout templates/uni_form/uni_form.html{% endcomment %}
    
</form>

cohpy_project/templates/library/_review_form.html
{% include "library/_form.html" %}

cohpy_project/templates/library/base_library.html
{% extends "site_base.html" %}
{% load i18n %}

{% block body_class %}books{% endblock %}

{% block body_outer %}
<div id="body">
    {% if messages %}
        <ul id="messages">
            {% for message in messages %}
            <li id="message_{{ forloop.counter }}"{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                <a href="#"><small>{% trans "clear" %}</small></a>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <h3>{% block content_title %}{% endblock %}</h3>
    
    {% block body %}
    {% endblock %}
    
</div>
{% endblock %}

cohpy_project/templates/library/book_detail.html
{% extends "library/base_library.html" %}
{% load library_tags frontendadmin_tags thumbnail %}

{% block title %}{{ object.full_title }}{% endblock %}


{% block content_title %}{% endblock %}


{% block body %}
  <h3>{{ object.full_title }}
    {% if object.subtitle %}<em>{{ object.subtitle }}</em>{% endif %}</h3>
  
  {% frontendadmin_change object %}
  
  {% if object.cover %}
  {% thumbnail object.cover 300x450 as cover %}
  <a class="cover" href="{{ object.amazon_url }}"><img src="{{ cover.url }}" alt="Book cover"></a>
  {% else %}
  <div class="no_cover"></div>
  {% endif %}
  
  <ul class="info_list">
    <li>Author: {{ book.author }}</a></li>
    {% if object.publisher %}
    <li>Publisher: <a href="{{ object.publisher.get_absolute_url }}">{{ object.publisher.full_title }}</a></li>
    {% endif %}
    {% if object.published %}
    <li>Released: {{ object.published|date:"d F Y" }}</li>
    {% endif %}
    
    {% if object.pages > 0 %}
    <li>Pages: {{ object.pages }} {% if not object.has_read %}on page {{ object.bookmark }}{% endif %}</li>
    {% endif %}

    {% if object.isbn %}
    <li>ISBN: {{ object.isbn }} (<a href="{{ object.amazon_url }}">Amazon</a>)</li>
    {% endif %}
  </ul>
  
  {% if object.description %}
  <div class="description">
    <h4>Description</h4>
    <p>
        {{ object.description|safe }}
    </p>
  </div>
  {% endif %}

  {% if request.user.is_authenticated %}
  <div class="checkout_status">
      {% if object.is_out %}
      <span>Out to {{ object.out_to.user }} {{ object.out_to.date|dayssince }}</span>
        {% if object.out_to.user == request.user %}
            <a href="{% url checkin object.pk object.out_to.pk "checkin" %}" rel="facebox">Checkin</a>
        {% endif %}
      {% else %}
        <a href="{% url checkout object.pk %}" rel="facebox">Checkout</a>
      {% endif %}
  </div>
  {% endif %}
  
  <div class="reviews">
      <h2><a href="{% url add_review object.pk %}" rel="facebox">Leave Review</a></h2>
      {% for review in object.review_set.all %}
      <div class="review">
          <span>{{ review.user }}</span> {{ review.stars }} of 5
          <dl>
          {% if review.why_did_you_get_this_book %}
              <dt>Why did you get this book?</dt>
              <dd>{{ review.why_did_you_get_this_book }}</dd>
          {% endif %}
          {% if review.did_you_like_it %}
              <dt>Did you Like it?</dt>
              <dd>{{ review.did_you_like_it }}</dd>
          {% endif %}
          </dl>
          {% frontendadmin_delete review %}
          
      </div>
      {% endfor %}
  </div>
  
  {% if object.checkout_set.all %}
  <div class="checkouts">
      <ul>
          <li>This Book has been checked out {{ object.checkout_set.all.count }} time{{ object.checkout_set.all.count|pluralize }}
          {% for checkout in object.checkout_set.all %}
          <li>{{ checkout.user }} {% if checkout.date_returned %}{{ checkout.date_returned|dayssince }}{%else%}checked out{% endif %}
          {% endfor %}
      </ul>
  </div>
  {% endif %}

{% endblock %}

cohpy_project/templates/library/book_list.html
{% extends "library/base_library.html" %}
{% load frontendadmin_tags %}

{% block title %}Books{% endblock %}


{% block content_title %}Books{% endblock %}


{% block body %}
  <dl>
  {% for book in object_list %}
    <dt>
      <a href="{{ book.get_absolute_url }}">{{ book.title }}{% if book.prefix %}, {{ book.prefix }}{% endif %}</a>
    </dt>
    <dd>
      <strong>{{ book.author }} <a href="{{ book.publisher.get_absolute_url }}">{{ book.publisher.full_title }}</a></strong>
      <p>
          {{ book.description|safe|truncatewords_html:30 }}
      </p>
    </dd>
  {% endfor %}
  </dl>
  {% frontendadmin_add object_list %}
{% endblock %}

cohpy_project/templates/library/checkout_form.html
{% extends "library/base_library.html" %}

{% block body %}
{% include "library/_checkout_form.html" %}
{% endblock %}

cohpy_project/templates/library/publisher_detail.html
{% extends "library/base_library.html" %}


{% block title %}{{ object.full_title }}{% endblock %}
{% block body_class %}{{ block.super }} book_publishers{% endblock %}


{% block content_title %}{% endblock %}


{% block body %}
  <h3>{{ object.full_title }}</h3>
  <ul class="link_list">
    {% for book in object.book_set.all %}
    <li><a href="{{ book.get_absolute_url }}">{{ book.full_title }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

cohpy_project/templates/library/publisher_list.html
{% extends "library/base_library.html" %}
{% load frontendadmin_tags %}

{% block title %}{{ object.full_title }}{% endblock %}
{% block body_class %}{{ block.super }} book_publishers{% endblock %}


{% block content_title %}Book Publishers{% endblock %}


{% block body %}
  <ul>
      {% for object in object_list %}
      <li><a href="{{object.get_absolute_url}}">{{ object.full_title }}</a>
      {% endfor %}
  </ul>
  {% frontendadmin_add object_list %}
{% endblock %}

cohpy_project/templates/library/review_form.html
{% extends "library/base_library.html" %}

{% block body %}
{% include "library/_review_form.html" %}
{% endblock %}